"""Static configuration for the CMA-ES market-maker experiment."""

from pathlib import Path


ROOT = Path(__file__).resolve().parent
ABIDES_CORE = ROOT / "abides_core"
RUNS_ROOT = ROOT / "historic_runs"
RUNS = RUNS_ROOT
HISTORIC_RUNS = RUNS_ROOT
EVALS = RUNS / "evals"

DEFAULT_LOB_FILE = (
    ROOT
    / "BenchmarkDatasets"
    / "BenchmarkDatasets"
    / "NoAuction"
    / "1.NoAuction_Zscore"
    / "NoAuction_Zscore_Training"
    / "Train_Dst_NoAuction_ZScore_CF_1.txt"
)
DEFAULT_LOB_DIR = DEFAULT_LOB_FILE.parent

DEFAULT_SECONDS = 40
DEFAULT_TIMEOUT = 600
DEFAULT_MINUTES = 1
DEFAULT_POPSIZE = 12
DEFAULT_GENS = 10
DEFAULT_MAX_EVALS = DEFAULT_POPSIZE * DEFAULT_GENS
DEFAULT_EARLY_STOP = 6

DEFAULT_SEEDS = [1, 2, 3, 4, 5, 6, 7, 8]
DEFAULT_DAYS = ["20200603"]
DEFAULT_TRAIN_SEEDS = [1, 2, 3, 4, 5, 6]
DEFAULT_VAL_SEEDS = [7, 8]
DEFAULT_TEST_SEEDS = [9, 10]
DEFAULT_TRAIN_DAYS = ["20200603"]
DEFAULT_VAL_DAYS = ["20200603"]
DEFAULT_TEST_DAYS = ["20200604"]

TRAIN_DATASET_COUNT = 5
VAL_DATASET_COUNT = 2
TEST_DATASET_COUNT = 2
WARMUP_GENERATIONS = 2
WARMUP_DATASET_AGG = "mean"
FULL_DATASET_AGG = "min"
DATASET_SPLIT_SEED = 1729

DEFAULT_INV_PENALTY = 10.0
DEFAULT_DRAWDOWN_THRESHOLD = 0.05
DEFAULT_DRAWDOWN_PENALTY = 100.0
DEFAULT_DRAWDOWN_CLIP = 1.5
DEFAULT_SCORE_TRIM = 0.25
DEFAULT_START_CASH = 10_000_000.0
DEFAULT_ROBUST_QUANTILE = 0.25
DEFAULT_LOSS_PENALTY = 10.0
DEFAULT_VALIDATION_WEIGHT = 0.25

DEFAULT_THIN = {
    "ValueAgent": 1,
    "NoiseAgent": 12,
    "MomentumAgent": 3,
    "ExecutionAgent": 1,
}

ANSI_RESET = "\033[0m"
ANSI_GREEN = "\033[32m"
ANSI_RED = "\033[31m"
ANSI_YELLOW = "\033[33m"
ANSI_BLUE = "\033[34m"
